db/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls', namespace="index")),

]

index/urls.py
from django.conf.urls import url
from django.contrib import admin

from index import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sql/$', views.sql_view, name='sql_view'),
    url(r'^sql_insert/$', views.sql_insert, name='sql_insert'),
    url(r'^table/$', views.table_view, name='table_view'),
    url(r'^table/(?P<table_name>.+)$', views.table_view, name='table_view'),
    url(r'^init/$', views.init_db, name='init_db'),
]

index/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

index/views.py
from django.shortcuts import render
from django.conf import settings
import unicodedata
import pickle
import miniDB
import sql
import re
import sys
sys.setrecursionlimit(5000)
import time

# Create your views here.
def index(request):
    return render(request,'index/index.html')

def sql_insert(request):
    sql_unicode = ""
    if request.FILES.get('filesql'):
        sqlfile = request.FILES.get('filesql')
        sql_unicode = sqlfile.read()
        
    elif request.POST.get('sql'):
        sql_unicode = request.POST['sql']

    # read DB from pkl file
    database = load_db()

    # apply sql to the database
    # (Bool,String) to indicate status of execution and error message
    sql_str = sql_unicode.encode('ascii','ignore')

    success, tables, err_msgs = [], [], []
    
    s, t, err = database.exec_insert(sql_str)

    save_db(database)

    data = {'sql':sql_str,
            #'info':zip(success, panel_msgs, sqlList, err_msgs, tables),
            }

    return render(request,'index/sql.html', data)

def sql_view(request):
    # to store input sql, make sure we receive the right input
    sql_str = "Input SQL will be shown here"

    if request.method == 'GET':
        data = {'sql':sql_str}
        return render(request,'index/sql.html', data)
    elif request.method == 'POST':
        sql_unicode = ""
        if request.FILES.get('filesql'):
            sqlfile = request.FILES.get('filesql')
            sql_unicode = sqlfile.read()
            
        elif request.POST.get('sql'):
            sql_unicode = request.POST['sql']

        # read DB from pkl file
        database = load_db()

        # apply sql to the database
        # (Bool,String) to indicate status of execution and error message
        sql_str = sql_unicode.encode('ascii','ignore')
        
        Uans = re.sub(r"\r\n"," ",sql_str)
        Uans = Uans.replace('\n', ' ')
        #print(Uans)
        #print("++++++++++++++")
        pattern = re.compile(";", re.IGNORECASE)
        st = pattern.sub(";\n", Uans)
        sqlList = [s.strip() for s in st.splitlines()]
        #print(sqlList)

        starttime = time.time()
        success, tables, err_msgs = [], [], []
        for small_sql in sqlList:
            s, t, err = database.exec_sql(small_sql)
            success.extend(s)
            tables.extend(t)
            err_msgs.extend(err)
        endtime = time.time()

        #print(tables)
        # additional message to indicate the execution is successful or not
        panel_msgs = []
        for s in success:
            if s:
                panel_msg = "success"
            else:
                panel_msg = "error"
            panel_msgs.append(panel_msg)

        save_db(database)

        data = {'sql':sql_str,
                'info':zip(success, panel_msgs, sqlList, err_msgs, tables),
                'used_time': endtime-starttime,
                }

        return render(request,'index/sql.html', data)
        
def table_view(request,table_name=None):
    # the db we want to view
    database = load_db()
    # retreive all table names
    table_names = database.get_all_table_names()
    # if user doesn't specify which table to view, choose the first one as default
    if table_name == None:
        try:
            table_name = table_names[0]
        except:
            return render(request,'index/table.html')
    
    table = database.get_table(table_name)
    
    data = {'table_names':table_names,
            'table_name':table_name,
            'columns':table.columns,
            'content':[row.values for row in table.entities]
            }
    return render(request,'index/table.html', data)

def init_db(request):
    if request.method == 'GET':
        return render(request,'index/init.html')
    elif request.method == 'POST':
        database = miniDB.Database()
        save_db(database)

        # fake
        data = {'success':True}
        return render(request,'index/init.html', data)

def save_db(database):
    # dump new db into a file
    output = open(settings.DB_NAME, 'wb')
    pickle.dump(database, output)

def load_db():
    # read DB from pkl file
    with open(settings.DB_NAME, 'rb') as f:
        return pickle.load(f)

index/templates/index/base.html
<head>
  <title>DB</title>
  {% load staticfiles %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Muli|Yanone+Kaffeesatz|Pacifico" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% block static_block %} {% endblock static_block %}
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index:index'%}">DB</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'index:sql_view'%}">SQL</a></li>
          <li><a href="{% url 'index:table_view'%}">Table</a></li>
          <li><a href="{% url 'index:init_db'%}">Init Database</a></li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
  <div class="body-block">
  {% block body_block %} {% endblock body_block %}
  </div>
</body>

index/templates/index/index.html
{% extends "index/base.html" %}
{% load staticfiles %}

{% block static_block %} 
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock static_block %}

{% block body_block %}
<h1 id="project-title">DB</h1>
<h3 id="author">by Erik, Garnix, Ron</h3>
{% endblock body_block %}

index/templates/index/init.html
{% extends "index/base.html" %}

{% load staticfiles %}

{% block static_block %} 
{% endblock static_block %}

{% block body_block %}
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-default" id="sql-submit" type="submit" value="Initiate Database">
    </form>
</div>
<hr>
{% if success %}
<div class="alert alert-success" role="alert">Init success!</div>
{% elif success == False %}
<div class="alert alert-danger" role="alert">Init Failed!</div>
{% endif %}

{% endblock body_block %}

index/templates/index/sql.html
{% extends "index/base.html" %}

{% load staticfiles %}

{% block static_block %} 
<link rel="stylesheet" href="{% static 'css/sql.css' %}">
{% endblock static_block %}

{% block body_block %}
<div class="form-group">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="sql">SQL</label>
        <textarea class="form-control" name="sql" id="sql" placeholder="Insert SQL here..."></textarea>
        <br>
        <input type="file" name="filesql" id="filesql">
        <input class="btn btn-default" id="sql-submit" type="submit" value="Submit">
    </form>
    <br>
    <form method="POST" enctype="multipart/form-data" action="{% url 'index:sql_insert'%}">
        {% csrf_token %}
        <input type="file" name="filesql" id="filesql">
        <input class="btn btn-primary" id="sql-insert-submit" type="submit" value="Submit Insert">
    </form>
</div>
<br>
<hr>
{% for info_row in info %}
{% if info_row.0 %}
<div class="panel panel-success">
{% elif info_row.0 == False %}
<div class="panel panel-danger">
{% else %}
<div class="panel panel-primary">
{% endif %}
<div class="panel-heading">
    <h3 class="panel-title">SQL execution {{ info_row.1 }}</h3>
  </div>
  <div class="panel-body">
    <p>{{ info_row.2 }}</p>
    <p class="danger">{{ info_row.3 }}</p>
    <p>Time: <b class="warning">{{ used_time }}</b> sec</p>
    {% if info_row.4 %}
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          {% for col in info_row.4.columns %}
          <th>{{ col.name }}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for ent in info_row.4.entities %}
        <tr>
          <td>{{ forloop.counter }}</td>
          {% for e in ent.values %}
          <td>{{ e }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>
{% endfor %}

{% endblock body_block %}

index/templates/index/table.html
{% extends "index/base.html" %}

{% load staticfiles %}

{% block static_block %} 
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<script src="{% static 'js/table.js' %}"></script>
{% endblock static_block %}

{% block body_block %}
{% if table_name %}
<h3>Choose one table to view</h3>
<select class="form-control" onchange="redirect(this.value)">
  {% for table in table_names %}
  {% if table == table_name %}
  <option value="{{ table }}" selected>{{ table }}</option>
  {% else %}
  <option value="{{ table }}">{{ table }}</option>
  {% endif %}
  {% endfor %}
</select>

<h3>{{ table_name }}</h3>
<table class="table">
    <tr>
      {% for col in columns %}
        {% if col.datatype == 1 %}
        <th>Int</th>
        {% elif col.datatype == 2 %}
        <th>Varchar({{ col.constraint.max_len }})</th>
        {% endif %}
      {% endfor %}
    </tr>
    <tr>
      {% for col in columns %}
        {% if col.key %}
        <th><u>{{ col.name }}<u></th>
        {% else %}
        <th>{{ col.name }}</th>
        {% endif %}
      {% endfor %}
    </tr>
    {% for row in content %}
    <tr>
      {% for col_content in row %}
        <td>{{ col_content }}</td>
      {% endfor %}
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No Table in the Database</p>
{% endif %}
{% endblock body_block %}